### ISSUE TITLE
hexo g error

### ISSUE THREAD

**Issue by iChrAlpha** [wzpan/hexo-renderer-pandoc#35]
After I use 
"sudo npm uninstall hexo-renderer-marked --save"
"sudo npm install hexo-renderer-pandoc --save"

and then type: 
hexo clean
hexo g 

It report this error:
```
Error: 
[ERROR][hexo-renderer-pandoc] On /Users/user/Documents/GitHub/ChrAlpha/aiguosb/source/_posts/p0-关于域名的测试.md
[ERROR][hexo-renderer-pandoc] pandoc exited with code null.
    at Hexo.pandocRenderer (/Users/user/Documents/GitHub/ChrAlpha/aiguosb/node_modules/hexo-renderer-pandoc/index.js:112:11)
    at Hexo.tryCatcher (/Users/user/Documents/GitHub/ChrAlpha/aiguosb/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/user/Documents/GitHub/ChrAlpha/aiguosb/node_modules/bluebird/js/release/method.js:15:34)
    at Promise.then.text (/Users/user/Documents/GitHub/ChrAlpha/aiguosb/node_modules/hexo/lib/hexo/render.js:60:20)
    at tryCatcher (/Users/user/Documents/GitHub/ChrAlpha/aiguosb/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/user/Documents/GitHub/ChrAlpha/aiguosb/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Users/user/Documents/GitHub/ChrAlpha/aiguosb/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromiseCtx (/Users/user/Documents/GitHub/ChrAlpha/aiguosb/node_modules/bluebird/js/release/promise.js:611:10)
    at _drainQueueStep (/Users/user/Documents/GitHub/ChrAlpha/aiguosb/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/Users/user/Documents/GitHub/ChrAlpha/aiguosb/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/user/Documents/GitHub/ChrAlpha/aiguosb/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/user/Documents/GitHub/ChrAlpha/aiguosb/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```
I have removed the 
`    if (config && config.template) {
      args.push("--template=" + config.template);
    }`
 in 
`node_modules/hexo-renderer-pandoc/index.js`

but it still didn't work...

After installing the package, I haven't changed the **ROOT** _config.yml or **nexT** _config.yml, except for the `math: enable: true` and `mathjax: enable: true`

**Comment by ChenglinYu** [comment]
You need to install Pandoc, and your pandoc's version must be at least 2.0.

**Comment by drriguz** [comment]
yes, I have the same issue after move to a new computer. I solved after [install pandoc](https://pandoc.org/installing.html) .

**Comment by Ritsuka314** [comment]
I'm closing this inactive issue. Seems the solution is to install Pancod. Feel free to reopen the issue if it is not resolved.
